### ISSUE TITLE
Makefile: line 14: Error -- FSUM8232 Expecting macro or rule defn, found n either

### ISSUE THREAD

**Issue by lsnakazone** [ibmruntimes/node-racf#1]
Hi,

I am trying to install the module on z / OS 2.3 and when trying to do npm install the following error happens:

make: Makefile: line 14: Error -- FSUM8232 Expecting macro or rule defn, found n
either

**Comment by pwelsh80** [comment]
Hi, 
I am having this issue also while trying to install the RACF Module into a node project on z/OS 2.4 
Is this issue related to the version of Make installed ? Is the default z/OS supplied version of make not satisfactory?   Make 4.1 seems to no longer be available from Rocket Software.  
is there a workaround for this problem  ?   

Cheers 
Patrick.

**Comment by pwelsh80** [comment]
Indeed the version of make is important and updating your PATH environment variable to use the correct version (gnu make v4.1 or later)of make fixed this issue for me.
